version: '3.8'
services:
  web:
    build:
      context: ./
      target: runner
    volumes:
      - .:/app
    command: npm run dev
    env_file:
      - ".env.local"
    ports:
      - "3000:3000"